import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({subsets: ['latin-ext']})


export const metadata = {
  title: 'AirNav Yogyakarta',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/ic_airnav.jpg" />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
